WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

STAGE_WIDTH = 960
STAGE_HEIGHT = 720

TEXT_PANEL_X = STAGE_WIDTH
TEXT_PANEL_WIDTH = WINDOW_WIDTH - STAGE_WIDTH
TEXT_PANEL_HEIGHT = WINDOW_HEIGHT

PANEL_PADDING = 24

CONSOLE_WIDTH = WINDOW_WIDTH / 2
CONSOLE_HEIGHT = WINDOW_HEIGHT / 2
CONSOLE_X = (WINDOW_WIDTH - CONSOLE_WIDTH) / 2
CONSOLE_Y = (WINDOW_HEIGHT - CONSOLE_HEIGHT) / 2
CONSOLE_CHECKBOX_SIZE = 18

SCRIPT_BACK_BUTTON_WIDTH = 72
SCRIPT_BACK_BUTTON_HEIGHT = 26
