WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

STAGE_WIDTH = 960
STAGE_HEIGHT = 720

TEXT_PANEL_X = STAGE_WIDTH
TEXT_PANEL_WIDTH = WINDOW_WIDTH - STAGE_WIDTH
TEXT_PANEL_HEIGHT = WINDOW_HEIGHT

PANEL_PADDING = 24

POPUP_WIDTH = WINDOW_WIDTH / 2
POPUP_HEIGHT = WINDOW_HEIGHT / 2
POPUP_X = (WINDOW_WIDTH - POPUP_WIDTH) / 2
POPUP_Y = (WINDOW_HEIGHT - POPUP_HEIGHT) / 2
